# Generated by Django 4.1.3 on 2022-11-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('constructors_championships', models.IntegerField()),
                ('drivers_championships', models.IntegerField()),
                ('race_wins', models.IntegerField()),
            ],
        ),
    ]
