# Generated by Django 4.1.3 on 2022-11-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='positions',
            field=models.ManyToManyField(to='main_app.position'),
        ),
    ]
